### ISSUE TITLE
Only hiding content locks notes (and other issues)

### ISSUE THREAD

**Issue by manaafi** [PotatoProject/Leaflet#5]
Only hiding the notes from the main page automatically locks it with some pin, making those notes unreadable.

Also, when a note is locked by a password, it shows up to enter a pin even when an alphanumerical password is set.

Another issue I've found is that when you open a note, no matter where you tap, the cursor always jumps to the starting position, and typing anything on the keyboard replaces the first word of the note.

**Comment by dvd-bnc** [comment]
Thanks for the report! I didn't actually note those bugs and I'm gonna fix them asap. The lock issues are because of some recent commits, i just have to check some commits and it should be fine. For the text thing, i don't really know what's causing the issue but i should have a workaround for that anyways

**Comment by dvd-bnc** [comment]
I fixed your issues on latest commits, thanks for the report
